# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orCeph_interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from portada import Ui_Form
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineSettings
from PyQt5.QtCore import QUrl


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, width, height):
        self.puntosSteiner = {
            'S': None,
            'N': None,
            'N\'': None,
            'Or': None,
            'Pr': None,
            'A': None,
            'A\'': None,
            'B': None,
            'B\'': None,
            'D': None,
            'Pg': None,
            'Pg\'': None,
            'Me': None,
            'Me\'': None,
            'Gn': None,
            'Gn\'': None,
            'Go': None,
            'Go\'': None,
            'III': None,
            'AII': None,
            'IIS': None,
            'AIS': None,
            'OMI': None,
            'OMS': None,
            'St': None,
            'LS': None,
            'LI': None,
            'ENP': None,
            'ENA': None,
            'Ar': None,
            'Prn': None,
            'Ba': None,
            'Po': None,
            'Pt': None,
            'Co': None,
            'G': None,
            'G\'': None,
            'Sn': None,
            'Sn\'': None,
            'Tm': None,
            'Tr': None
        }

        self.puntosDistancia = {
            'PuntoA': None,
            'PuntoB': None
        }

        self.planos = {}

        self.angulos = {}

        self.pixelUnidad = None;

        self.distanciaInput = None
        self.unidadInput = None

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(width, height - 70)
        MainWindow.move(0,0)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setGeometry(QtCore.QRect(width-1220, 10, 250, 10))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_doctor = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_doctor.setFont(font)
        self.lbl_doctor.setObjectName("lbl_doctor")
        self.horizontalLayout_7.addWidget(self.lbl_doctor)

        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setGeometry(QtCore.QRect(width-950, 10, 250, 10))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_paciente = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_paciente.setFont(font)
        self.lbl_paciente.setObjectName("lbl_paciente")
        self.horizontalLayout_8.addWidget(self.lbl_paciente)

        self.widget_12 = QtWidgets.QWidget(self.centralwidget)
        self.widget_12.setGeometry(QtCore.QRect(width-675, 10, 250, 15))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbl_imagen = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_imagen.setFont(font)
        self.lbl_imagen.setObjectName("lbl_imagen")
        self.horizontalLayout_9.addWidget(self.lbl_imagen)

        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setGeometry(QtCore.QRect(width-1220, 25, 250, 25))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_nombreD = QtWidgets.QLabel(self.widget_8)
        self.lbl_nombreD.setObjectName("lbl_nombreD")
        self.horizontalLayout_5.addWidget(self.lbl_nombreD)
        self.input_nombreD = QtWidgets.QLineEdit(self.widget_8)
        self.input_nombreD.setObjectName("input_nombreD")
        self.horizontalLayout_5.addWidget(self.input_nombreD, 2)

        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setGeometry(QtCore.QRect(width-1220, 50, 250, 38))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_cedula = QtWidgets.QLabel(self.widget_9)
        self.lbl_cedula.setObjectName("lbl_cedula")
        self.horizontalLayout_6.addWidget(self.lbl_cedula)
        self.input_cedula = QtWidgets.QLineEdit(self.widget_9)
        self.input_cedula.setObjectName("input_ceduña")
        self.horizontalLayout_6.addWidget(self.input_cedula, 2)


        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(width-950, 25, 250, 25))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_nombreP = QtWidgets.QLabel(self.widget_7)
        self.lbl_nombreP.setObjectName("lbl_nombreP")
        self.horizontalLayout_4.addWidget(self.lbl_nombreP)
        self.input_nombreP = QtWidgets.QLineEdit(self.widget_7)
        self.input_nombreP.setObjectName("input_nombreP")
        self.horizontalLayout_4.addWidget(self.input_nombreP, 2)


        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(width - 950, 50, 250, 38))
        #self.widget_6.setStyleSheet('background:red')
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout3.setContentsMargins(0,0,0,0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.lbl_edad = QtWidgets.QLabel(self.widget_6)
        self.lbl_edad.setObjectName("lbl_edad")
        self.horizontalLayout3.addWidget(self.lbl_edad, 1)
        self.input_edad = QtWidgets.QSpinBox(self.widget_6)
        self.input_edad.setObjectName("input_edad")
        self.horizontalLayout3.addWidget(self.input_edad, 2)
        self.lbl_sexo = QtWidgets.QLabel(self.widget_6)
        self.lbl_sexo.setObjectName("lbl_sexo")
        self.horizontalLayout3.addWidget(self.lbl_sexo, 1)
        self.select_sexo = QtWidgets.QComboBox(self.widget_6)
        self.select_sexo.setObjectName("select_unidad")
        self.select_sexo.addItem("")
        self.select_sexo.addItem("")
        self.select_sexo.addItem("")
        self.horizontalLayout3.addWidget(self.select_sexo, 4)


        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(width - 675, 50, 350, 38))
        self.widget_2.setObjectName("widget_2")
        #self.widget_2.setStyleSheet('background:blue')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_ditancia = QtWidgets.QLabel(self.widget_2)
        self.lbl_ditancia.setObjectName("lbl_ditancia")
        self.horizontalLayout.addWidget(self.lbl_ditancia)
        self.input_medida = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.input_medida.setEnabled(False)
        self.input_medida.setObjectName("input_medida")
        self.horizontalLayout.addWidget(self.input_medida)
        self.select_unidad = QtWidgets.QComboBox(self.widget_2)
        self.select_unidad.setObjectName("select_unidad")
        self.select_unidad.setEnabled(False)
        self.select_unidad.addItem("")
        self.select_unidad.addItem("")
        self.select_unidad.addItem("")
        self.horizontalLayout.addWidget(self.select_unidad)
        self.btn_aceptarDistancia = QtWidgets.QPushButton(self.widget_2)
        self.btn_aceptarDistancia.setObjectName("btn_aceptarDistancia")
        self.horizontalLayout.addWidget(self.btn_aceptarDistancia)
        self.btn_aceptarDistancia.setEnabled(False)

        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        #self.widget_3.setStyleSheet("background:'red'")
        self.widget_3.setGeometry(QtCore.QRect(width - 310, 10, 300, height - 350))
        self.widget_3.setObjectName("widget_3")
        self.lbl_lista = QtWidgets.QLabel(self.widget_3)
        self.lbl_lista.setGeometry(QtCore.QRect(10, 0, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lista.setFont(font)
        self.lbl_lista.setObjectName("lbl_lista")
        self.line = QtWidgets.QFrame(self.widget_3)
        self.line.setGeometry(QtCore.QRect(10, 20, 281, 5))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        ### SCROLL BAR
        self.formLayout = QFormLayout()
        self.groupBox = QGroupBox("Selecciona un punto:")
        self.labelList = []
        self.buttonList = []
        i = 0
        for k,v in self.puntosSteiner.items():
            self.labelList.append(QLabel(f"{k}:"))
            self.buttonList.append(QPushButton("Colocar Punto"))
            self.buttonList[i].setEnabled(False)
            self.formLayout.addRow(self.labelList[i], self.buttonList[i])
            i = i + 1

        self.groupBox.setLayout(self.formLayout)
        self.scroll = QScrollArea()
        self.scroll.setWidget(self.groupBox)
        self.scroll.setWidgetResizable(True)
        self.scroll.setFixedHeight(height-400)

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.scroll)

        self.widget_3.setLayout(self.layout)

        self.btn_reajustar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reajustar.setGeometry(QtCore.QRect(width - 300, 740, 281, 41))
        self.btn_reajustar.setObjectName("btn_reajustar")
        self.btn_reajustar.setEnabled(False)

        self.btn_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcular.setGeometry(QtCore.QRect(width - 300, 790, 281, 41))
        self.btn_calcular.setObjectName("btn_calcular")
        self.btn_calcular.setEnabled(False)


        self.btn_verPuntos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verPuntos.setGeometry(QtCore.QRect(width - 300, 840, 281, 41))
        self.btn_verPuntos.setObjectName("btn_calcular")
        self.btn_verPuntos.setEnabled(False)

        self.btn_verPlanos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verPlanos.setGeometry(QtCore.QRect(width - 300, 890, 130, 41))
        self.btn_verPlanos.setObjectName("btn_verPlanos")
        self.btn_verPlanos.setEnabled(False)

        self.btn_descargarTrazado = QtWidgets.QPushButton(self.centralwidget)
        self.btn_descargarTrazado.setGeometry(QtCore.QRect(width - 150, 890, 130, 41))
        self.btn_descargarTrazado.setObjectName("btn_descargarInforme")
        self.btn_descargarTrazado.setEnabled(False)

        self.btn_verResultados = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verResultados.setGeometry(QtCore.QRect(width - 300, 940, 130, 41))
        self.btn_verResultados.setObjectName("btn_verResultados")
        self.btn_verResultados.setEnabled(False)

        self.btn_descargarInforme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_descargarInforme.setGeometry(QtCore.QRect(width - 150, 940, 130, 41))
        self.btn_descargarInforme.setObjectName("btn_descargarInforme")
        self.btn_descargarInforme.setEnabled(False)


        # self.btn_verAngulos = QtWidgets.QPushButton(self.centralwidget)
        # self.btn_verAngulos.setGeometry(QtCore.QRect(width - 150, 850, 130, 41))
        # self.btn_verAngulos.setObjectName("btn_verAngulos")
        # self.btn_verAngulos.setEnabled(False)

        ######### PDF VIEWER ######
        self.layout_pdf = QVBoxLayout()
        self.widget_13 = QtWidgets.QWidget(self.centralwidget)
        self.widget_13.setGeometry(QtCore.QRect(10, 85, 1600, 900))
        #self.widget_13.setStyleSheet("background:red")
        self.widget_13.setLayout(self.layout_pdf)
        self.web_view = QWebEngineView()
        self.layout_pdf.addWidget(self.web_view)
        self.web_view.settings().setAttribute(QWebEngineSettings.PluginsEnabled, True)
        self.web_view.settings().setAttribute(QWebEngineSettings.PdfViewerEnabled, True)
        self.widget_13.hide()


        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(-5, 85, 1620, 920))
        self.widget_5.setObjectName("widget_5")

        self.photo = PhotoLabel(self.widget_5)
        self.photo.setObjectName("photo")
        self.photo.setFixedSize(1591, 891)

        self.scroll2 = QScrollArea()
        self.scroll2.setWidget(self.photo)
        self.scroll2.setWidgetResizable(True)
        self.scroll2.setFixedSize(1610,900)
        self.scroll2.setStyleSheet("border: none;")
        
        self.layout2 = QVBoxLayout()
        self.layout2.addWidget(self.scroll2)
        self.widget_5.setLayout(self.layout2)

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 650, 60))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_titulo = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.verticalLayout.addWidget(self.lbl_titulo)
        self.lbl_indicacion = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_indicacion.setFont(font)
        self.lbl_indicacion.setObjectName("lbl_indicacion")
        self.verticalLayout.addWidget(self.lbl_indicacion)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(width-675, 25, 350, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_radiografia = QtWidgets.QLabel(self.widget1)
        self.lbl_radiografia.setObjectName("lbl_radiografia")
        self.horizontalLayout_2.addWidget(self.lbl_radiografia)
        self.btn_buscar = QtWidgets.QPushButton(self.widget1)
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_2.addWidget(self.btn_buscar, 2)

        stack = QStackedWidget()
        MainWindow.setStyleSheet("background:white")
        self.portada = Portada(stack, width, height, MainWindow)
        stack.addWidget(self.portada)
        stack.addWidget(self.centralwidget)
        stack.setCurrentIndex(0)
        MainWindow.setCentralWidget(stack)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1086, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "orCeph"))
        self.lbl_ditancia.setText(_translate("MainWindow", "Distancia entre los puntos:"))
        self.select_unidad.setItemText(0, _translate("MainWindow", "mm"))
        self.select_unidad.setItemText(1, _translate("MainWindow", "cm"))
        self.select_unidad.setItemText(2, _translate("MainWindow", "in"))
        self.lbl_lista.setText(_translate("MainWindow", "Lista de Puntos de Steiner:"))
        self.lbl_nombreD.setText(_translate("MainWindow", "Nombre:"))
        self.lbl_nombreP.setText(_translate("MainWindow", "Nombre:"))
        self.lbl_cedula.setText(_translate("MainWindow", "Cedula: "))
        self.lbl_doctor.setText(_translate("MainWindow", "Datos del Doctor: "))
        self.lbl_imagen.setText(_translate("MainWindow", "Sobre la radiografía: "))
        self.lbl_paciente.setText(_translate("MainWindow", "Datos del Paciente: "))
        self.lbl_edad.setText(_translate("MainWindow", "Edad:"))
        self.lbl_sexo.setText(_translate("MainWindow", "Sexo:"))
        self.select_sexo.setItemText(0, _translate("MainWindow", ""))
        self.select_sexo.setItemText(1, _translate("MainWindow", "Femenino"))
        self.select_sexo.setItemText(2, _translate("MainWindow", "Masculino"))
        self.btn_calcular.setText(_translate("MainWindow", "Calcular"))
        self.btn_reajustar.setText(_translate("MainWindow", "Colocar Distancia"))
        self.lbl_titulo.setText(_translate("MainWindow", "¡Bienvenido a OrCeph!"))
        self.lbl_indicacion.setText(_translate("MainWindow", "Ingrese la radiografía que desea analizar:"))
        self.lbl_radiografia.setText(_translate("MainWindow", "Ingrese la radiografía:       "))
        self.btn_buscar.setText(_translate("MainWindow", "Buscar Imagen"))
        self.btn_aceptarDistancia.setText(_translate("MainWindow", "Aceptar"))
        self.btn_descargarInforme.setText(_translate("MainWindow", "Descargar Informe"))
        self.btn_descargarTrazado.setText(_translate("MainWindow", "Descargar Trazado"))
        self.btn_verPlanos.setText(_translate("MainWindow", "Visualizar Planos"))
        #self.btn_verAngulos.setText(_translate("MainWindow", "Visualizar Angulos"))
        self.btn_verPuntos.setText(_translate("MainWindow", "Recolocar Puntos"))
        self.btn_verResultados.setText(_translate("MainWindow", "Visualizar Informe"))


class Portada(QtWidgets.QWidget):
    def __init__(self, stack, width, height, MainWindow, parent=None):
        super().__init__(parent)
        self.main_window = MainWindow
        self.ui = Ui_Form()
        self.ui.setupUi(self, stack, width, height)
        self.ui.pushButton.clicked.connect(self.changePage)
    def changePage(self):
        self.main_window.setStyleSheet("background: None")
        self.ui.stack.setCurrentIndex(1)


class PhotoLabel(QLabel):

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setAlignment(Qt.AlignCenter)
        self.main_window = None
        self.posicion = [0,0]
        self.posicion_anterior = [0,0]
        self.pixmap = None
        self.qp = None
        self.pen = None
        self.punto = ""
        self.distancia = False
        self.setText('\n\n Drop Image Here \n\n')
        self.setStyleSheet('''
        QLabel {
            border: 4px dashed #aaa;
        }''')


    def setPixmap(self, *args, **kwargs):
        self.pixmap = QPixmap(*args, **kwargs)
        self.pixmap_temp = QPixmap(*args, **kwargs)
        self.pixmapPlanos = None
        #self.pixmapAngulos = None
        self.main_window = None
        super().setPixmap(self.pixmap)
        super().setScaledContents(True)
        self.setStyleSheet('''
        QLabel {
            border: none;
        }''')

    def setPoint(self,texto, num_button, main_window):
        if(self.pixmap != None):
            self.punto = texto
            self.numbutton = num_button
            self.main_window = main_window

    def setDistancia(self, main_window):
        if(self.pixmap != None):
            self.main_window = main_window
            self.distancia = True
        if(self.main_window.puntosDistancia['PuntoA'] != None and self.main_window.puntosDistancia['PuntoB'] != None):
            self.main_window.lbl_indicacion.setText("Coloque los dos puntos de distancia nuevamente:")
            self.qp = QPainter(self.pixmap)
            if(self.main_window.puntosDistancia['PuntoA'][1] > self.main_window.puntosDistancia['PuntoB'][1]):
                puntoYmenor = self.main_window.puntosDistancia['PuntoB'][1]
                puntoYmayor = self.main_window.puntosDistancia['PuntoA'][1]
            else:
                puntoYmenor = self.main_window.puntosDistancia['PuntoA'][1]
                puntoYmayor = self.main_window.puntosDistancia['PuntoB'][1]
            if(self.main_window.puntosDistancia['PuntoA'][0] > self.main_window.puntosDistancia['PuntoB'][0]):
                puntoXmenor = self.main_window.puntosDistancia['PuntoB'][0]
                puntoXmayor = self.main_window.puntosDistancia['PuntoA'][0]
            else:
                puntoXmenor = self.main_window.puntosDistancia['PuntoA'][0]
                puntoXmayor = self.main_window.puntosDistancia['PuntoB'][0]
            for i in range(puntoXmenor-10, puntoXmayor+10):
                for j in range(puntoYmenor-10, puntoYmayor+10):
                    print(f'{i}, {j}')
                    bg_color = QColor(self.pixmap_temp.toImage().pixel(i, j))
                    self.qp.setPen(QPen(bg_color, 1))
                    self.qp.drawPoint(i,j) 
            self.qp.end()
            super().setPixmap(self.pixmap)
            self.main_window.puntosDistancia['PuntoA'] = None
            self.main_window.puntosDistancia['PuntoB'] = None
            self.main_window.select_unidad.setEnabled(False)
            self.main_window.input_medida.setEnabled(False)
            self.main_window.input_medida.setValue(0)
            self.main_window.btn_aceptarDistancia.setEnabled(False)

    def drawPlano(self, puntoA, puntoB):
        if(self.pixmapPlanos == None):
            self.pixmapPlanos = QPixmap(self.pixmap)
        self.qp = QPainter(self.pixmapPlanos)
        self.pen = QPen(QColor(242,192,50), 5)
        self.qp.setPen(self.pen)
        self.qp.drawLine(puntoA[0], puntoA[1], puntoB[0], puntoB[1])
        self.qp.end()

    #def drawAngulo(self,puntoA, puntoB, puntoC):
    #    if(self.pixmapAngulos == None):
    #        self.pixmapAngulos = QPixmap(self.pixmap)
    #    self.qp = QPainter(self.pixmapAngulos)
    #    self.pen = QPen(Qt.blue, 5)
    #    self.qp.setPen(self.pen)
    #    self.qp.drawLine(puntoA[0], puntoA[1], puntoB[0], puntoB[1])
    #    self.qp.drawLine(puntoB[0], puntoB[1], puntoC[0], puntoC[1])
    #    self.qp.end()
        

    def showPuntos(self):
        self.main_window.widget_13.hide()
        self.main_window.widget_5.show()
        super().setPixmap(self.pixmap)

    def showPlanos(self):
        self.main_window.widget_13.hide()
        self.main_window.widget_5.show()
        super().setPixmap(self.pixmapPlanos)

    #def showAngulos(self):
    #    super().setPixmap(self.pixmapAngulos)


    def mousePressEvent(self, event):
        if(event.buttons() & Qt.LeftButton):
            self.posicion[0] = event.pos().x()
            self.posicion[1] = event.pos().y()
            print(self.posicion)
            self.update()

            if(self.distancia == False and self.punto != "" and self.main_window != None and self.main_window.puntosSteiner[self.punto] == None):
                print("Punto seleccionado")
                self.qp = QPainter(self.pixmap)
                self.pen = QPen(QColor(57,255,20), 9)
                self.qp.setPen(self.pen)
                #print(self.posicion)
                self.qp.drawPoint(self.posicion[0],self.posicion[1])
                self.qp.drawText(self.posicion[0]+5,self.posicion[1]-5, self.punto)
                self.main_window.buttonList[self.numbutton].setText(f"({self.posicion[0]},{self.posicion[1]})")
                # self.posicion_anterior[0] = self.posicion[0]
                # self.posicion_anterior[1] = self.posicion[1]
                self.main_window.puntosSteiner[self.punto] = (self.posicion[0], self.posicion[1])
                self.qp.end()
                super().setPixmap(self.pixmap)
            elif(self.distancia == False and self.main_window != None and self.main_window.puntosSteiner[self.punto] != None):
                self.qp = QPainter(self.pixmap)
                self.posicion_anterior[0] = self.main_window.puntosSteiner[self.punto][0]
                self.posicion_anterior[1] = self.main_window.puntosSteiner[self.punto][1]
                for i in range(self.posicion_anterior[0]-4, self.posicion_anterior[0]+5):
                    for j in range(self.posicion_anterior[1]-4, self.posicion_anterior[1]+5):
                        bg_color = QColor(self.pixmap_temp.toImage().pixel(i, j))
                        self.qp.setPen(QPen(bg_color, 1))
                        self.qp.drawPoint(i,j)
                for i in range (self.posicion_anterior[0]+4, self.posicion_anterior[0]+35):
                    for j in range(self.posicion_anterior[1]-14, self.posicion_anterior[1]-3):
                        bg_color = QColor(self.pixmap_temp.toImage().pixel(i, j))
                        self.qp.setPen(QPen(bg_color, 1))
                        self.qp.drawPoint(i,j)
                self.pen = QPen(QColor(57,255,20), 9)
                self.qp.setPen(self.pen)
                self.qp.drawPoint(self.posicion[0],self.posicion[1])
                self.qp.drawText(self.posicion[0]+10,self.posicion[1]-5, self.punto)
                self.main_window.puntosSteiner[self.punto] = (self.posicion[0], self.posicion[1])
                self.qp.end()
                super().setPixmap(self.pixmap)
            elif(self.distancia and self.main_window != None):
                if(self.main_window.puntosDistancia['PuntoA'] == None):
                    self.qp = QPainter(self.pixmap)
                    self.pen = QPen(Qt.white, 5)
                    self.qp.setPen(self.pen)
                    self.qp.drawPoint(self.posicion[0],self.posicion[1])
                    self.main_window.puntosDistancia['PuntoA'] = (self.posicion[0], self.posicion[1])
                    self.qp.end()
                    super().setPixmap(self.pixmap)
                elif(self.main_window.puntosDistancia['PuntoB'] == None):
                    self.qp = QPainter(self.pixmap)
                    self.pen = QPen(Qt.white, 5)
                    self.qp.setPen(self.pen)
                    self.qp.drawPoint(self.main_window.puntosDistancia['PuntoA'][0],self.posicion[1])
                    self.main_window.puntosDistancia['PuntoB'] = (self.main_window.puntosDistancia['PuntoA'][0], self.posicion[1])
                    self.qp.drawLine(self.main_window.puntosDistancia['PuntoA'][0], self.main_window.puntosDistancia['PuntoA'][1], self.main_window.puntosDistancia['PuntoB'][0], self.main_window.puntosDistancia['PuntoB'][1])
                    self.qp.end()
                    super().setPixmap(self.pixmap)
                    self.main_window.lbl_indicacion.setText("Coloque la distancia entre los puntos:")
                    self.main_window.input_medida.setEnabled(True)
                    self.main_window.select_unidad.setEnabled(True)
                    self.main_window.btn_aceptarDistancia.setEnabled(True)
                    self.main_window.btn_reajustar.setText("Reajustar Distancia")


