# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orCeph_interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, width, height):
        self.puntosSteiner = {
            'S':(21,32),
            'N':(15,12),
            'N\'':(13,12),
            'Or':(13,11),
            'Pr': None,
            'A':(32,64),
            'A\'':(17,13),
            'B':(43,54),
            'B\'':(15,65),
            'D':(13,67),
            'Pg':(54,14),
            'Pg\'':(24,76),
            'Me':(83,4),
            'Me\'':(19,12),
            'Gn': None,
            'Gn\'':(19,12),
            'Go':(83,4),
            'Go\'':(19,12),
            'III':(54,4),
            'AII':(83,4),
            'IIS':(83,4),
            'AIS':(19,12),
            'OMI':(83,4),
            'OMS':(83,4),
            'St':(83,4),
            'LS':(83,4),
            'LI':(83,4),
            'ENP':(83,4),
            'ENA':(83,4),
            'Ar':(83,4),
            'Prn':(83,4),
            'Ba':(83,4),
            'Po':(83,4),
            'Pt':(83,4),
            'Co':(83,4),
            'G':(83,4),
            'G\'':(83,4),
            'Sn':(83,4),
            'Sn\'':(83,4),
            'Tm':(83,4),
            'Tr': None
        }
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(width, height - 70)
        MainWindow.move(0,0)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(width - 300, 110, 280, 38))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_ditancia = QtWidgets.QLabel(self.widget_2)
        self.lbl_ditancia.setObjectName("lbl_ditancia")
        self.horizontalLayout.addWidget(self.lbl_ditancia)
        self.input_medida = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.input_medida.setObjectName("input_medida")
        self.horizontalLayout.addWidget(self.input_medida)
        self.select_unidad = QtWidgets.QComboBox(self.widget_2)
        self.select_unidad.setObjectName("select_unidad")
        self.select_unidad.addItem("")
        self.select_unidad.addItem("")
        self.select_unidad.addItem("")
        self.horizontalLayout.addWidget(self.select_unidad)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(width - 300, 160, 281, height - 350))
        self.widget_3.setObjectName("widget_3")
        self.lbl_lista = QtWidgets.QLabel(self.widget_3)
        self.lbl_lista.setGeometry(QtCore.QRect(10, 20, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lista.setFont(font)
        self.lbl_lista.setObjectName("lbl_lista")
        self.line = QtWidgets.QFrame(self.widget_3)
        self.line.setGeometry(QtCore.QRect(10, 30, 261, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        ### SCROLL BAR
        self.formLayout = QFormLayout()
        self.groupBox = QGroupBox("Selecciona un punto:")
        self.labelList = []
        self.buttonList = []
        i = 0
        for k,v in self.puntosSteiner.items():
            self.labelList.append(QLabel(f"{k}:"))
            if v != None:
                self.buttonList.append(QPushButton(f"{v}"))
            else:
                self.buttonList.append(QPushButton("Colocar Punto"))
            self.formLayout.addRow(self.labelList[i], self.buttonList[i])
            i = i + 1

        self.groupBox.setLayout(self.formLayout)
        self.scroll = QScrollArea()
        self.scroll.setWidget(self.groupBox)
        self.scroll.setWidgetResizable(True)
        self.scroll.setFixedHeight(height-450)

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.scroll)

        self.widget_3.setLayout(self.layout)



        self.btn_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcular.setGeometry(QtCore.QRect(width - 290, 900, 261, 41))
        self.btn_calcular.setObjectName("btn_calcular")

        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(-5, 0, 1700, 1080))
        self.widget_5.setObjectName("widget_5")

        self.photo = PhotoLabel(self.widget_5)
        self.photo.setObjectName("photo")
        self.photo.setFixedSize(1591, 891)

        self.scroll2 = QScrollArea()
        self.scroll2.setWidget(self.photo)
        self.scroll2.setWidgetResizable(True)
        self.scroll2.setFixedSize(1610,900)
        self.scroll2.setStyleSheet("border: none;")
        
        self.layout2 = QVBoxLayout()
        self.layout2.addWidget(self.scroll2)
        self.widget_5.setLayout(self.layout2)

        # self.imagen = QtWidgets.QLabel(self.centralwidget)
        # self.imagen.setGeometry(QtCore.QRect(30, 150, width-400, height-250))
        # self.imagen.setObjectName("imagen")
        # self.imagen.setStyleSheet('''
        # QLabel {
        #     border: 4px dashed #aaa;
        # }''')

        ### BOTONES ZOOM 

        # self.btn_mas = QtWidgets.QPushButton(self.centralwidget)
        # self.btn_mas.setGeometry(QtCore.QRect(width-350, height-580, 41, 23))
        # self.btn_mas.setObjectName("btn_mas")
        # self.btn_menos = QtWidgets.QPushButton(self.centralwidget)
        # self.btn_menos.setGeometry(QtCore.QRect(width-350, height-550, 41, 23))
        # self.btn_menos.setObjectName("btn_menos")
        # self.lbl_zoom = QtWidgets.QLabel(self.centralwidget)
        # self.lbl_zoom.setGeometry(QtCore.QRect(width-350, height-600, 41, 16))
        # self.lbl_zoom.setObjectName("lbl_zoom")

        ####### 

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 536, 60))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_titulo = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.verticalLayout.addWidget(self.lbl_titulo)
        self.lbl_indicacion = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_indicacion.setFont(font)
        self.lbl_indicacion.setObjectName("lbl_indicacion")
        self.verticalLayout.addWidget(self.lbl_indicacion)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(width-300, 70, 281, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_radiografia = QtWidgets.QLabel(self.widget1)
        self.lbl_radiografia.setObjectName("lbl_radiografia")
        self.horizontalLayout_2.addWidget(self.lbl_radiografia)
        self.btn_buscar = QtWidgets.QPushButton(self.widget1)
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_2.addWidget(self.btn_buscar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1086, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "orCeph"))
        self.lbl_ditancia.setText(_translate("MainWindow", "Distancia entre los puntos:"))
        self.select_unidad.setItemText(0, _translate("MainWindow", "mm"))
        self.select_unidad.setItemText(1, _translate("MainWindow", "cm"))
        self.select_unidad.setItemText(2, _translate("MainWindow", "in"))
        self.lbl_lista.setText(_translate("MainWindow", "Lista de Puntos de Steiner:"))
        self.btn_calcular.setText(_translate("MainWindow", "Calcular"))
        #self.imagen.setText(_translate("MainWindow", "Imagen"))
        # self.btn_mas.setText(_translate("MainWindow", "+"))
        # self.btn_menos.setText(_translate("MainWindow", "-"))
        # self.lbl_zoom.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Zoom</p></body></html>"))
        self.lbl_titulo.setText(_translate("MainWindow", "¡Bienvenido a OrCeph!"))
        self.lbl_indicacion.setText(_translate("MainWindow", "Coloque dos puntos de los cuales conozca la distancia entre ellos:"))
        self.lbl_radiografia.setText(_translate("MainWindow", "Ingrese la radiografía: "))
        self.btn_buscar.setText(_translate("MainWindow", "Buscar Imagen"))

class PhotoLabel(QLabel):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setAlignment(Qt.AlignCenter)
        self.posicion = [0,0]
        self.pixmap = None
        self.qp = None
        self.pen = None
        self.punto = ""
        self.setText('\n\n Drop Image Here \n\n')
        self.setStyleSheet('''
        QLabel {
            border: 4px dashed #aaa;
        }''')


    def setPixmap(self, *args, **kwargs):
        self.pixmap = QPixmap(*args, **kwargs)
        #qp = QPainter(pixmap)
        #pen = QPen(Qt.white, 5)
        #qp.setPen(pen)
        # self.point = QPoint(200+10,200-5)
        # self.qp.drawPoint(0,0);
        # self.qp.drawText(self.point, "S")
        # self.qp.end()
        super().setPixmap(self.pixmap)
        super().setScaledContents(True)
        self.setStyleSheet('''
        QLabel {
            border: none;
        }''')

    def setPoint(self, texto):
        if(self.pixmap != None):
            self.punto = texto
            # qp.drawPoint(self.posicion[0],self.posicion[1])
            # qp.drawText(self.posicion[0]+10,self.posicion[1]-5, texto)
            # super().setPixmap(self.pixmap)
            # print("Fin del punto")

    def mousePressEvent(self, event):
        if(event.buttons() & Qt.LeftButton):
            self.posicion[0] = event.pos().x()
            self.posicion[1] = event.pos().y()
            print(self.posicion)
            self.update()
            if(self.punto != "" and self.punto != "S"):
                print("Punto seleccionado")
                self.qp = QPainter(self.pixmap)
                self.pen = QPen(Qt.white, 9)
                self.qp.setPen(self.pen)
                print(self.posicion)
                self.qp.drawPoint(self.posicion[0],self.posicion[1])
                self.qp.drawText(self.posicion[0]+10,self.posicion[1]-5, self.punto)
                self.qp.end()
                super().setPixmap(self.pixmap)
