# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portada.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):    
    def setupUi(self, Form, stack, width, height):
        self.stack = stack
        Form.setObjectName("Form")
        Form.resize(width, height - 70)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(width-810, 350, 241, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(width-900, 450, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 120, 700, 800))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Politecnico/Logo Steiner.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(width-800, 540, 211, 51))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(width-350, height-120, 350, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(width-200, 20, 71, 81))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Politecnico/Poli.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(width-100, 20, 91, 81))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Politecnico/Escom.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">OrCeph</p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Analizador Cefalométrico de Steiner</p></body></html>"))
        self.pushButton.setText(_translate("Form", "Iniciar"))
        self.label_4.setText(_translate("Form", "© Ismael Ortega Estrada, IPN ESCOM. Todos los derechos reservados."))

import Poli_rc
